on: [pull_request]

jobs:
    build:
        name: Comment a pull_request
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Deploy to vercel
              uses: mb2dev/github-action-comment-pull-request@1.0.0
              with:
                message: "Pre-Deploy가 완성되었습니다."
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                reactions: "+1 | -1 | laugh | hooray | confused | heart | rocket | eyes"

            - name: Check storyboard
              uses: mb2dev/github-action-comment-pull-request@1.0.0
              with:
                message: "Srtoryboard를 확인하세요"
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                reactions: "+1 | -1 | laugh | hooray | confused | heart | rocket | eyes"
